USE school;
DELETE FROM student;

INSERT INTO student (STDID,FIRSTNAME,LASTNAME,MAJOR) values ('64130500170','SOMCHAI','JAIDEE','IT');
INSERT INTO student (STDID,FIRSTNAME,LASTNAME,MAJOR) values ('64130500280','PETER','CHU', 'CS');
INSERT INTO student (STDID,FIRSTNAME,LASTNAME,MAJOR) values ('64130500460','SOMSRI','RAKREAN', 'DSI');
